function spd = testDTcal(nRepeats, filename)
%trying to make a simple function that will measure the spectra of light
%generated by my DT stimuli. Basically I'll measure the same stimulus
%nRepeats times and then return the average spectra. 

S = [380, 4, 101];  % Native PR650 settings
spd = nan(101, nRepeats);
CMCheckInit(1)
for a = 1:nRepeats;
    advance = 0;
    clc
    fprintf('Press Space Bar to continue\n');
    while ~advance
        [keyisdown,secs,keycode] = KbCheck();
        if (keycode(KbName('space'))) %if you press the space bar
            advance = 1;
            clc
        end
    end
    sprintf('Measuring Spectra. Repeat <%d>', a);
    tmp = PR650measspd(S)
    spd(:,a) = tmp(:);
end

if nRepeats > 1
spd = mean(spd,2);
end

if ~exist('filename', 'var')
    filename = 'monSpect.mat';
end


