function [] = GLMS_AnalysisGUI(~,~)
global GLMP
% This code calls different analyses for Grid LM Subunit datasets

% Set up Control Panel
b = figure(30); clf;
set(b,'DefaultAxesUnits','normalized','position',[1100 400 275 550],...
    'UserData',[],'NumberTitle','off','Name',['Control Panel (' GLMP.datafile ')'],...
    'MenuBar','none','ToolBar','none')
cpanel = get(b,'UserData');

% Create Panels
cpanel.axes.dnpanel = uipanel('Position',[.025 .51 .95 .475],'Title','Dense Noise Controls','Parent',b);
cpanel.axes.glmppanel = uipanel('Position',[.025 .025 .95 .475],'Title','GLMP Controls','Parent',b);

% DN Panel
dnpanel = get(cpanel.axes.dnpanel,'UserData');
dnpanel.analyses.stixeltimecourse = uicontrol('Parent',cpanel.axes.dnpanel,'Units','pixels',...
    'style','pushbutton','string','Stixel Time Course',...
    'Position',[20 20 100 40],'Callback',@GLMSGUI_StixelTC);
dnpanel.analyses.differencemaps = uicontrol('Parent',cpanel.axes.dnpanel,'Units','pixels',...
    'style','pushbutton','string','Difference Maps',...
    'position',[20 70 100 40],'callback',@GLMSGUI_DiffMaps);
dnpanel.analyses.filter = uicontrol('parent',cpanel.axes.dnpanel,'Units','pixels',...
    'style','pushbutton','string','Filter Analysis',...
    'pos',[20 120 100 40],'callback',@GLMSGUI_FilterAnalysis);
dnpanel.analyses.cluster = uicontrol('parent',cpanel.axes.dnpanel,'Units','pixels',...
    'style','pushbutton','string','Cluster Analysis',...
    'pos',[20 170 100 40],'callback',@GLMSGUI_ClusterAnalysis);
dnpanel.analyses.comparetoGLMP = uicontrol('parent',cpanel.axes.dnpanel,'Units','pixels',...
    'style','pushbutton','string','Compare DN to GLMP',...
    'pos',[140 70 100 40],'callback',@GLMSGUI_CompareDNGLMP);

% GLMP Panel
glmppanel = get(cpanel.axes.glmppanel,'UserData');
glmppanel.analyses.PSTH = uicontrol('Style','pushbutton','string','PSTH',...
    'parent',cpanel.axes.glmppanel,'units','pixels','pos',[20 20 100 40],...
    'Callback',@GLMSGUI_PSTH);
glmppanel.analyses.CRF = uicontrol('Style','pushbutton','string','CRF',...
    'parent',cpanel.axes.glmppanel,'units','pixels','pos',[20 70 100 40],...
    'Callback',@GLMSGUI_CRF);
glmppanel.analyses.surf = uicontrol('Style','pushbutton','string','Surface',...
    'parent',cpanel.axes.glmppanel,'units','pixels','pos',[20 120 100 40],...
    'Callback',{@GLMSGUI_Surface});
glmppanel.analyses.TC = uicontrol('Style','pushbutton','string','Time Course',...
    'parent',cpanel.axes.glmppanel,'units','pixels','pos',[20 170 100 40],...
    'Callback',@GLMSGUI_StimTC);
glmppanel.analyses.SpikeStats = uicontrol('Style','pushbutton','string','Spike Stats',...
    'parent',cpanel.axes.glmppanel,'units','pixels','pos',[140 20 100 40],...
    'Callback',@GLMSGUI_GLMPSpikeStats);
glmppanel.analyses.mean2var = uicontrol('Style','pushbutton','string','Mean to Var',...
    'parent',cpanel.axes.glmppanel,'units','pixels','pos',[140 70 100 40],...
    'Callback',@GLMSGUI_Mean2Var);
glmppanel.analyses.ConfInt = uicontrol('Style','pushbutton','string','Mean to Var',...
    'parent',cpanel.axes.glmppanel,'units','pixels','pos',[140 120 100 40],...
    'Callback',@GLMSGUI_ConfidenceIntervals);

set(cpanel.axes.dnpanel,'UserData',dnpanel)
set(cpanel.axes.glmppanel,'UserData',glmppanel)
set(b,'UserData',cpanel)


end